import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/services/LoginService/QueryProvider";
import { AuthProvider } from "@/services/Context/AuthContext";
import { Toaster } from "react-hot-toast";
import NavbarComponent from "@/views/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>

        <QueryProvider>
          <NavbarComponent />
          {children}
          <Toaster position="top-right" />
        </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
